version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-service
    restart: always
    environment:
      MYSQL_DATABASE: wigellrepairs
      MYSQL_USER: wigell
      MYSQL_PASSWORD: wigell
      MYSQL_ROOT_PASSWORD: wigell
    ports:
      - "3307:3306"  # host:container
    networks:
      - wigell
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wigellrepairs:
    build: .  # assumes you have a Dockerfile in the current directory
    container_name: wigellrepairs
    depends_on:
      mysql-service:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/wigellrepairs
      SPRING_DATASOURCE_USERNAME: wigell
      SPRING_DATASOURCE_PASSWORD: wigell
      # Optional: override port if defined in application.properties
      SERVER_PORT: 5555
    ports:
      - "5555:5555"  # host:container
    networks:
      - wigell

networks:
  wigell:
    external: true  # assumes you already created this network
